CREATE TABLE token
(
    id         INTEGER NOT NULL PRIMARY KEY,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    revoked    BOOLEAN NOT NULL,
    expired    BOOLEAN NOT NULL,
    user_id    VARCHAR(255)
);

ALTER TABLE token ADD CONSTRAINT uc_token_token UNIQUE (token);
ALTER TABLE token ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES auth_user (username);

ALTER TABLE token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
