name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
    paths: frontend/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: LatexScribe/LatexScribe.github.io
          personal_token: ${{ secrets.WORKFLOW }}
          publish_dir: frontend/dist/angular-latex/browser
          enable_jekyll: true
          allow_empty_commit: true
          force_orphan: true
